/* MTI_DPI */

/*
 * Copyright 2002-2008 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_MAC_FEDRIVER
#define INCLUDED_MAC_FEDRIVER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


typedef struct {
	int		reset;
	int 		RBempty;
	int		read_data1;
	int		read_data2;
	int		read_data3;
	int		read_data4;
} read_data_type_in;

typedef struct {
	int		readRB;
} read_data_type_out;

typedef struct {
	int 		reset;
	int		AFfull;
	int		WBfull;
} write_data_type_in;

typedef struct {
	int	 	writeAF;		// write addr fifo
	int		read;			// read command
	int		addr;			// address
	int 		writeWB;		// write buffer write enable
	int 		write_data1;
	int 		write_data2;
	int 		write_data3;
	int 		write_data4;
} write_data_type_out;

DPI_LINK_DECL DPI_DLLESPEC
void
init_driver();

DPI_LINK_DECL DPI_DLLESPEC
void
do_read(
    const read_data_type_in* rdata_in, read_data_type_out* rdata_out);

DPI_LINK_DECL DPI_DLLESPEC
void
do_write(
    const write_data_type_in* wdata_in, write_data_type_out* wdata_out);

#endif 
