onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/gclk
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/rst
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/eth2speedtm
add wave -noupdate -childformat {{/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.tid -radix hexadecimal} {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.valid -radix hexadecimal} {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.run -radix hexadecimal} {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.replay -radix hexadecimal} {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.retired -radix hexadecimal} {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.inst -radix hexadecimal} {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.paddr -radix hexadecimal} {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.npc -radix hexadecimal}} -expand -subitemconfig {/sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.tid {-radix hexadecimal} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.valid {-radix hexadecimal} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.run {-radix hexadecimal} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.replay {-radix hexadecimal} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.retired {-radix hexadecimal} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.inst {-radix hexadecimal} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.paddr {-radix hexadecimal} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm.npc {-radix hexadecimal}} /sim_top/sim/gen_cpu/checkpt_tm/cpu2tm
add wave -noupdate -expand /sim_top/sim/gen_cpu/checkpt_tm/tm2cpu
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/running
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/done
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/checkpt_tm/v_tid_out
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/checkpt_tm/v_ncores
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/checkpt_tm/v_tid_dma
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/checkpt_tm/tid_dma
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/checkpt_tm/tid_out
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/checkpt_tm/ncores
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/v_running
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/v_done
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/v_instr_store
add wave -noupdate /sim_top/sim/gen_cpu/checkpt_tm/instr_store
add wave -noupdate /sim_top/sim/gen_cpu_control/clk
add wave -noupdate /sim_top/sim/gen_cpu_control/reset
add wave -noupdate /sim_top/sim/gen_cpu_control/gclk
add wave -noupdate /sim_top/sim/gen_cpu_control/rx_pipe_in
add wave -noupdate /sim_top/sim/gen_cpu_control/rx_pipe_out
add wave -noupdate /sim_top/sim/gen_cpu_control/tx_ring_in
add wave -noupdate /sim_top/sim/gen_cpu_control/tx_ring_out
add wave -noupdate /sim_top/sim/gen_cpu_control/dma_cmd_in
add wave -noupdate /sim_top/sim/gen_cpu_control/dma_done
add wave -noupdate /sim_top/sim/gen_cpu_control/dma_rb_in
add wave -noupdate /sim_top/sim/gen_cpu_control/dma_rb_out
add wave -noupdate /sim_top/sim/gen_cpu_control/dma_wb_in
add wave -noupdate /sim_top/sim/gen_cpu_control/sberr
add wave -noupdate /sim_top/sim/gen_cpu_control/dberr
add wave -noupdate /sim_top/sim/gen_cpu_control/luterr
add wave -noupdate /sim_top/sim/gen_cpu_control/mem_data_in
add wave -noupdate /sim_top/sim/gen_cpu_control/mem_data_out
add wave -noupdate /sim_top/sim/gen_cpu_control/mem_data_out_valid
add wave -noupdate /sim_top/sim/gen_cpu_control/poll_not_ready
add wave -noupdate /sim_top/sim/gen_cpu_control/eth_mem_rd
add wave -noupdate /sim_top/sim/gen_cpu_control/valid_out
add wave -noupdate /sim_top/sim/gen_cpu_control/eth2speedtm
add wave -noupdate /sim_top/sim/gen_cpu_control/speedtm_running
add wave -noupdate /sim_top/sim/gen_cpu_control/vstate
add wave -noupdate /sim_top/sim/gen_cpu_control/rstate
add wave -noupdate /sim_top/sim/gen_cpu_control/v_rx_pipe_out
add wave -noupdate /sim_top/sim/gen_cpu_control/v_tx_ring_out
add wave -noupdate /sim_top/sim/gen_cpu_control/isRetry
add wave -noupdate /sim_top/sim/gen_cpu_control/next_addr
add wave -noupdate /sim_top/sim/gen_cpu_control/next_count
add wave -noupdate /sim_top/sim/gen_cpu_control/cmd_fifo_din
add wave -noupdate /sim_top/sim/gen_cpu_control/cmd_fifo_dout
add wave -noupdate /sim_top/sim/gen_cpu_control/cmd_fifo_we
add wave -noupdate /sim_top/sim/gen_cpu_control/cmd_fifo_re
add wave -noupdate /sim_top/sim/gen_cpu_control/cmd_fifo_empty
add wave -noupdate /sim_top/sim/gen_cpu_control/cmd_fifo_rst
add wave -noupdate /sim_top/sim/gen_cpu_control/le_data
add wave -noupdate /sim_top/sim/gen_cpu_control/r_dma_done
add wave -noupdate /sim_top/sim/gen_cpu_control/mem_data_send
add wave -noupdate /sim_top/sim/gen_cpu_control/mem_data_en
add wave -noupdate /sim_top/sim/gen_cpu_control/mem_data_in_seg
add wave -noupdate /sim_top/sim/gen_cpu_control/poll_delay_count
add wave -noupdate /sim_top/sim/gen_cpu_control/v_poll_delay_count
add wave -noupdate /sim_top/sim/gen_cpu_control/mem_rd_store
add wave -noupdate /sim_top/sim/gen_cpu_control/eth_rb_in
add wave -noupdate /sim_top/sim/gen_cpu_control/eth_wb_in
add wave -noupdate /sim_top/sim/gen_cpu_control/eth_wb_out
add wave -noupdate /sim_top/sim/gen_cpu/gclk
add wave -noupdate /sim_top/sim/gen_cpu/rst
add wave -noupdate /sim_top/sim/gen_cpu/dma_rb_in
add wave -noupdate /sim_top/sim/gen_cpu/dma_rb_out
add wave -noupdate /sim_top/sim/gen_cpu/dma_wb_in
add wave -noupdate /sim_top/sim/gen_cpu/dma_cmd_in
add wave -noupdate /sim_top/sim/gen_cpu/dma_cmd_ack
add wave -noupdate /sim_top/sim/gen_cpu/dma2tm
add wave -noupdate /sim_top/sim/gen_cpu/dma_done
add wave -noupdate /sim_top/sim/gen_cpu/error1_led
add wave -noupdate /sim_top/sim/gen_cpu/error2_led
add wave -noupdate /sim_top/sim/gen_cpu/luterr
add wave -noupdate /sim_top/sim/gen_cpu/bramerr
add wave -noupdate /sim_top/sim/gen_cpu/sb_ecc
add wave -noupdate /sim_top/sim/gen_cpu/tm_pkt_in
add wave -noupdate /sim_top/sim/gen_cpu/tm_pkt_out
add wave -noupdate /sim_top/sim/gen_cpu/tm_pkt_valid
add wave -noupdate /sim_top/sim/gen_cpu/eth_mem_rd
add wave -noupdate /sim_top/sim/gen_cpu/valid_out
add wave -noupdate /sim_top/sim/gen_cpu/speedtm_running
add wave -noupdate /sim_top/sim/gen_cpu/eth2speedtm
add wave -noupdate /sim_top/sim/gen_cpu/pc_count
add wave -noupdate /sim_top/sim/gen_cpu/count_state
add wave -noupdate /sim_top/sim/gen_cpu/xc_error_mode
add wave -noupdate /sim_top/sim/gen_cpu/xc_error_r
add wave -noupdate /sim_top/sim/gen_cpu/xc_error_out
add wave -noupdate /sim_top/sim/gen_cpu/stopct_pc
add wave -noupdate /sim_top/sim/gen_cpu/error_pc
add wave -noupdate /sim_top/sim/gen_cpu/comr
add wave -noupdate /sim_top/sim/gen_cpu/der
add wave -noupdate /sim_top/sim/gen_cpu/regr
add wave -noupdate /sim_top/sim/gen_cpu/exr
add wave -noupdate /sim_top/sim/gen_cpu/memr
add wave -noupdate /sim_top/sim/gen_cpu/xcr
add wave -noupdate /sim_top/sim/gen_cpu/immu_if_in
add wave -noupdate /sim_top/sim/gen_cpu/immu_de_out
add wave -noupdate /sim_top/sim/gen_cpu/ex2mem_dmmu
add wave -noupdate /sim_top/sim/gen_cpu/mmu2hc
add wave -noupdate /sim_top/sim/gen_cpu/mmu2hc_invalid
add wave -noupdate /sim_top/sim/gen_cpu/iu2dmmu
add wave -noupdate /sim_top/sim/gen_cpu/dmmu2iu
add wave -noupdate /sim_top/sim/gen_cpu/dmmu2immu
add wave -noupdate /sim_top/sim/gen_cpu/itlb_miss
add wave -noupdate /sim_top/sim/gen_cpu/dtlb_miss
add wave -noupdate /sim_top/sim/gen_cpu/icache_if_in
add wave -noupdate /sim_top/sim/gen_cpu/icache_if_out
add wave -noupdate /sim_top/sim/gen_cpu/icache_de_out
add wave -noupdate /sim_top/sim/gen_cpu/icache_de_in
add wave -noupdate /sim_top/sim/gen_cpu/icache_mem2iu_stat
add wave -noupdate /sim_top/sim/gen_cpu/icache_iu2mem_tid
add wave -noupdate /sim_top/sim/gen_cpu/icache_iu2mem_cmd
add wave -noupdate /sim_top/sim/gen_cpu/icache_mem2cacheram
add wave -noupdate /sim_top/sim/gen_cpu/icache_cacheram2mem
add wave -noupdate /sim_top/sim/gen_cpu/dcache_data
add wave -noupdate /sim_top/sim/gen_cpu/iu2dcache
add wave -noupdate /sim_top/sim/gen_cpu/dcache2mmu
add wave -noupdate /sim_top/sim/gen_cpu/dcache2iu
add wave -noupdate /sim_top/sim/gen_cpu/dcache_mem2iu_stat
add wave -noupdate /sim_top/sim/gen_cpu/dcache_iu2mem_tid
add wave -noupdate /sim_top/sim/gen_cpu/dcache_iu2mem_cmd
add wave -noupdate /sim_top/sim/gen_cpu/dcache_mem2cacheram
add wave -noupdate /sim_top/sim/gen_cpu/dcache_cacheram2mem
add wave -noupdate /sim_top/sim/gen_cpu/iu2dma
add wave -noupdate /sim_top/sim/gen_cpu/dma2iu
add wave -noupdate /sim_top/sim/gen_cpu/dma_rtid
add wave -noupdate /sim_top/sim/gen_cpu/cpu2tm_out
add wave -noupdate /sim_top/sim/gen_cpu/replay_out
add wave -noupdate /sim_top/sim/gen_cpu/dma2cpu
add wave -noupdate /sim_top/sim/gen_cpu/tm2cpu
add wave -noupdate /sim_top/sim/gen_cpu/tm2cpu_final
add wave -noupdate /sim_top/sim/gen_cpu/tm2cpu_tm
add wave -noupdate /sim_top/sim/gen_cpu/r_tm2cpu
add wave -noupdate /sim_top/sim/gen_cpu/v_tm2cpu
add wave -noupdate /sim_top/sim/gen_cpu/tm2cpu_tid_inc
add wave -noupdate /sim_top/sim/gen_cpu/running
add wave -noupdate /sim_top/sim/gen_cpu/tick
add wave -noupdate /sim_top/sim/gen_cpu/replay_empty
add wave -noupdate /sim_top/sim/gen_cpu/replay_full
add wave -noupdate /sim_top/sim/gen_cpu/replay_data_rdy
add wave -noupdate /sim_top/sim/gen_cpu/replay_data_read
add wave -noupdate /sim_top/sim/gen_cpu/mem_out_empty
add wave -noupdate /sim_top/sim/gen_cpu/mem_out_full
add wave -noupdate /sim_top/sim/gen_cpu/speedtm_done
add wave -noupdate /sim_top/sim/gen_cpu/replay_out_short
add wave -noupdate /sim_top/sim/gen_cpu/tm_pkt_out_1
add wave -noupdate /sim_top/sim/gen_cpu/tm_pkt_out_2
add wave -noupdate /sim_top/sim/gen_cpu/v_tid
add wave -noupdate /sim_top/sim/gen_cpu/io_in
add wave -noupdate /sim_top/sim/gen_cpu/io_out
add wave -noupdate /sim_top/sim/gen_cpu/irq_io_out
add wave -noupdate /sim_top/sim/gen_cpu/tm_io_out
add wave -noupdate /sim_top/sim/gen_cpu/irqack
add wave -noupdate /sim_top/sim/gen_cpu/irq_timer
add wave -noupdate /sim_top/sim/gen_cpu/luterr_r
add wave -noupdate /sim_top/sim/gen_cpu/if_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/de_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/ex_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/xc_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/imem_if_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/dmem_if_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/dma_luterr
add wave -noupdate /sim_top/sim/gen_cpu/dramctrl_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/dmmu_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/immu_lutram_err
add wave -noupdate /sim_top/sim/gen_cpu/bramerr_r
add wave -noupdate /sim_top/sim/gen_cpu/de_bram_err
add wave -noupdate /sim_top/sim/gen_cpu/ex_bram_err
add wave -noupdate /sim_top/sim/gen_cpu/xc_bram_err
add wave -noupdate /sim_top/sim/gen_cpu/dmmu_dberr
add wave -noupdate /sim_top/sim/gen_cpu/immu_dberr
add wave -noupdate /sim_top/sim/gen_cpu/r_dmmu_dberr
add wave -noupdate /sim_top/sim/gen_cpu/r_immu_dberr
add wave -noupdate /sim_top/sim/gen_cpu/sb_ecc_r
add wave -noupdate /sim_top/sim/gen_cpu/de_sb_ecc
add wave -noupdate /sim_top/sim/gen_cpu/xc_sb_ecc
add wave -noupdate /sim_top/sim/gen_cpu/dmmu_sberr
add wave -noupdate /sim_top/sim/gen_cpu/immu_sberr
add wave -noupdate /sim_top/sim/gen_cpu/r_dmmu_sberr
add wave -noupdate /sim_top/sim/gen_cpu/r_immu_sberr
add wave -noupdate /sim_top/sim/gen_cpu/luterr_out
add wave -noupdate /sim_top/sim/gen_cpu/bramerr_out
add wave -noupdate /sim_top/sim/gen_cpu/sb_ecc_out
add wave -noupdate /sim_top/sim/gen_cpu/dcacheblkcnt
add wave -noupdate /sim_top/sim/gen_cpu/dcacherawcnt
add wave -noupdate /sim_top/sim/gen_cpu/hostcycle_en
add wave -noupdate /sim_top/sim/gen_cpu/icmiss_en
add wave -noupdate /sim_top/sim/gen_cpu/ldmiss_en
add wave -noupdate /sim_top/sim/gen_cpu/itlbmiss_en
add wave -noupdate /sim_top/sim/gen_cpu/dtlbmiss_en
add wave -noupdate /sim_top/sim/gen_cpu/stmiss_en
add wave -noupdate /sim_top/sim/gen_cpu/nretired_en
add wave -noupdate /sim_top/sim/gen_cpu/ldst_en
add wave -noupdate /sim_top/sim/gen_cpu/blkcnt_en
add wave -noupdate /sim_top/sim/gen_cpu/rawcnt_en
add wave -noupdate /sim_top/sim/gen_cpu/replay_en
add wave -noupdate /sim_top/sim/gen_cpu/idlecnt_en
add wave -noupdate /sim_top/sim/gen_cpu/microcode_en
add wave -noupdate /sim_top/sim/gen_cpu/replaymul_en
add wave -noupdate /sim_top/sim/gen_cpu/replayfpu_en
add wave -noupdate /sim_top/sim/gen_cpu/comr_r_run
add wave -noupdate /sim_top/sim/gen_cpu/comr_run
add wave -noupdate /sim_top/sim/gen_cpu/comr_r_dma
add wave -noupdate /sim_top/sim/gen_cpu/comr_dma
add wave -noupdate /sim_top/sim/gen_cpu/host_global_perf_counter
add wave -noupdate /sim_top/sim/clkin_p
add wave -noupdate /sim_top/sim/clkin_n
add wave -noupdate /sim_top/sim/clk200_p
add wave -noupdate /sim_top/sim/clk200_n
add wave -noupdate /sim_top/sim/rstin
add wave -noupdate /sim_top/sim/cpurst
add wave -noupdate /sim_top/sim/RxD
add wave -noupdate /sim_top/sim/TxD
add wave -noupdate /sim_top/sim/ddr2_dq
add wave -noupdate /sim_top/sim/ddr2_a
add wave -noupdate /sim_top/sim/ddr2_ba
add wave -noupdate /sim_top/sim/ddr2_ras_n
add wave -noupdate /sim_top/sim/ddr2_cas_n
add wave -noupdate /sim_top/sim/ddr2_we_n
add wave -noupdate /sim_top/sim/ddr2_cs_n
add wave -noupdate /sim_top/sim/ddr2_odt
add wave -noupdate /sim_top/sim/ddr2_cke
add wave -noupdate /sim_top/sim/ddr2_dm
add wave -noupdate /sim_top/sim/ddr2_dqs
add wave -noupdate /sim_top/sim/ddr2_dqs_n
add wave -noupdate /sim_top/sim/ddr2_ck
add wave -noupdate /sim_top/sim/ddr2_ck_n
add wave -noupdate /sim_top/sim/error1_led
add wave -noupdate /sim_top/sim/error2_led
add wave -noupdate /sim_top/sim/PHY_TXD
add wave -noupdate /sim_top/sim/PHY_TXEN
add wave -noupdate /sim_top/sim/PHY_TXER
add wave -noupdate /sim_top/sim/PHY_GTXCLK
add wave -noupdate /sim_top/sim/PHY_RXD
add wave -noupdate /sim_top/sim/PHY_RXDV
add wave -noupdate /sim_top/sim/PHY_RXER
add wave -noupdate /sim_top/sim/PHY_RXCLK
add wave -noupdate /sim_top/sim/PHY_RESET
add wave -noupdate /sim_top/sim/gclk
add wave -noupdate /sim_top/sim/rst
add wave -noupdate /sim_top/sim/eth_rst
add wave -noupdate /sim_top/sim/eth_rb_in
add wave -noupdate /sim_top/sim/eth_wb_in
add wave -noupdate /sim_top/sim/eth_wb_out
add wave -noupdate /sim_top/sim/dma_rb_in
add wave -noupdate /sim_top/sim/dma_rb_out
add wave -noupdate /sim_top/sim/dma_wb_in
add wave -noupdate /sim_top/sim/dma_cmd_in
add wave -noupdate /sim_top/sim/dma_done
add wave -noupdate /sim_top/sim/dma2tm
add wave -noupdate /sim_top/sim/tm_data_to_host
add wave -noupdate /sim_top/sim/tm_data_from_cpu
add wave -noupdate /sim_top/sim/tm_data_to_cpu
add wave -noupdate /sim_top/sim/mem_data_out_valid
add wave -noupdate /sim_top/sim/valid_out
add wave -noupdate /sim_top/sim/eth2speedtm
add wave -noupdate /sim_top/sim/speedtm_running
add wave -noupdate /sim_top/sim/eth_tm_reset
add wave -noupdate /sim_top/sim/cpu_reset
add wave -noupdate /sim_top/sim/clk_p
add wave -noupdate /sim_top/sim/cpu_seu
add wave -noupdate /sim_top/sim/ram_clk
add wave -noupdate /sim_top/sim/dramrst
add wave -noupdate /sim_top/sim/clk200
add wave -noupdate /sim_top/sim/clk200x
add wave -noupdate /sim_top/sim/dramfifo_error
add wave -noupdate /sim_top/sim/eth_mem_rd
add wave -noupdate /sim_top/sim/dma_buf_sberr
add wave -noupdate /sim_top/sim/dma_buf_dberr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {560497579 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 400
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {560350119 ps} {560862087 ps}
