onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_txp
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_txn
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_rxp
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_rxn
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/sys_clk_p
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/sys_clk_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/sys_reset_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/clk
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_data_in
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_data_in_valid
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/pcie_interface/pcie_data_out
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/mem_cnt_eq
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/mem_out_empty
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/rd_addr_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/rd_be_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/rd_data_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_addr_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_addr_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_be_fpga
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/pcie_interface/wr_be_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_data_fpga
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/pcie_interface/wr_data_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_en_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_en_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_busy_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/ready
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/refclkout
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/clk
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rst_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_data_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_en_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_busy_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data_raw_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data0_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data1_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data2_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data3_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/write_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/post_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_mem_state
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data0_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data1_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data2_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data3_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/DW0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/DW1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/DW2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data0_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data1_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data2_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data3_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/state_ascii
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/clk
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rst_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_data_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_en_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_busy_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data_raw_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data0_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data1_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data2_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data3_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/write_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/post_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_mem_state
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data0_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data1_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data2_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data3_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/DW0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/DW1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/DW2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data0_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data1_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data2_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data3_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/state_ascii
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {56478852 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 772
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {41652122 ps} {71305582 ps}
