onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_txp
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_txn
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_rxp
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pci_exp_rxn
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/sys_clk_p
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/sys_clk_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/sys_reset_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/clk
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_data_in
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_data_in_valid
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/pcie_interface/pcie_data_out
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/mem_cnt_eq
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/mem_out_empty
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/rd_addr_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/rd_be_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/rd_data_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_addr_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_addr_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_be_fpga
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/pcie_interface/wr_be_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_data_fpga
add wave -noupdate -radix hexadecimal /sim_top/sim/gen_cpu/pcie_interface/wr_data_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_en_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_en_fpga2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/wr_busy_fpga
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/ready
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/refclkout
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/clk
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rst_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_data_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_en_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_busy_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data_raw_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data0_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data1_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data2_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data3_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/write_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/post_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/wr_mem_state
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data0_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data1_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data2_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/pre_wr_data3_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/DW0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/DW1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/DW2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_pre_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/w_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data0_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data1_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data2_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/rd_data3_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/state_ascii
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/clk
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rst_n
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_addr_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_be_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_data_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_en_i
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_busy_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data_raw_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data0_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data1_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data2_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data3_o
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/write_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/post_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/wr_mem_state
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data0_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data1_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data2_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/pre_wr_data3_q
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/DW0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/DW1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/DW2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_pre_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b3
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b2
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b1
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/w_wr_data_b0
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data0_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data1_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data2_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/rd_data3_en
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_R/state_ascii
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEOUTLATA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEOUTREGA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEOUTLATB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEOUTREGB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DOA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DOB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DOPA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DOPB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/ENA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CLKA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/SSRA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEINLATA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEINREGA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/REGCEA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/ENB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CLKB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/SSRB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEINLATB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/CASCADEINREGB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/REGCEB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/ADDRA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/ADDRB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DIA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DIB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DIPA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/DIPB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/WEA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/WEB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/GSR
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/dangle_out8
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/dangle_out
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/dangle_out4
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem32/dangle_out32
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEOUTLATA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEOUTREGA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEOUTLATB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEOUTREGB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DOA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DOB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DOPA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DOPB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/ENA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CLKA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/SSRA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEINLATA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEINREGA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/REGCEA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/ENB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CLKB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/SSRB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEINLATB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/CASCADEINREGB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/REGCEB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/ADDRA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/ADDRB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DIA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DIB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DIPA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/DIPB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/WEA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/WEB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/GSR
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/dangle_out8
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/dangle_out
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/dangle_out4
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem64/dangle_out32
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEOUTLATA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEOUTREGA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEOUTLATB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEOUTREGB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DOA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DOB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DOPA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DOPB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/ENA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CLKA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/SSRA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEINLATA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEINREGA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/REGCEA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/ENB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CLKB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/SSRB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEINLATB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/CASCADEINREGB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/REGCEB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/ADDRA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/ADDRB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DIA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DIB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DIPA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/DIPB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/WEA
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/WEB
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/GSR
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/dangle_out8
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/dangle_out
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/dangle_out4
add wave -noupdate /sim_top/sim/gen_cpu/pcie_interface/pcie_hw/app/PIO/PIO_EP/EP_MEM_W/EP_MEM/ep_mem_erom/dangle_out32
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {56478852 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 772
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {4975413 ps}
