/* MTI_DPI */

/*
 * Copyright 2002-2009 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_TM_TEST
#define INCLUDED_TM_TEST

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


typedef struct {
    svBit valid;
    svBit run;
    svBitVecVal tid[SV_PACKED_DATA_NELEMS(6)];
    svBit running;
} tm2cpu_token_type;

typedef struct {
    svBitVecVal tid[SV_PACKED_DATA_NELEMS(6)];
    svBit valid;
    svBit run;
    svBit replay;
    svBit retired;
    svBitVecVal inst[SV_PACKED_DATA_NELEMS(32)];
    svBitVecVal paddr[SV_PACKED_DATA_NELEMS(32)];
    svBitVecVal npc[SV_PACKED_DATA_NELEMS(32)];
} tm_cpu_ctrl_token_type;

typedef struct {
    svBitVecVal irl[SV_PACKED_DATA_NELEMS(4)];
    svBitVecVal rdata[SV_PACKED_DATA_NELEMS(32)];
    svBit retry;
} io_bus_out_type;

typedef struct {
    svBitVecVal tid[SV_PACKED_DATA_NELEMS(6)];
    svBitVecVal addr[SV_PACKED_DATA_NELEMS(20)];
    svBitVecVal wdata[SV_PACKED_DATA_NELEMS(32)];
    svBit rw;
    svBit en;
    svBit replay;
    svBitVecVal we[SV_PACKED_DATA_NELEMS(4)];
    svBit wtid_valid;
} io_bus_in_type;

DPI_LINK_DECL DPI_DLLESPEC
int
init_simulator(
    const char* cmdline,
    int ncores,
    int silent);

DPI_LINK_DECL DPI_DLLESPEC
int
tick_simulator(
    const tm2cpu_token_type* tm2cpu,
    tm_cpu_ctrl_token_type* cpu2tm,
    const io_bus_out_type* io_tm2cpu,
    io_bus_in_type* io_cpu2tm);

#endif 
